//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SectionCatalogue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UKSections {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UKSections() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectionCatalogue.UKSections", typeof(UKSections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHS21X2.6,1.20,0.0213,0.0026,0.00015,6.81E-09,0.00000064,0.00000092,0.00668000,0.00000001,0.00000000
        ///CHS21X2.9,1.32,0.0213,0.0029,0.00017,7.27E-09,0.00000068,0.00000099,0.00659000,0.00000001,0.00000000
        ///CHS21X3.2,1.43,0.0213,0.0032,0.00018,7.68E-09,0.00000072,0.00000106,0.00650000,0.00000002,0.00000000
        ///CHS27X2.6,1.56,0.0269,0.0026,0.0002,1.48E-08,0.00000110,0.00000154,0.00864000,0.00000003,0.00000000
        ///CHS27X2.9,1.72,0.0269,0.0029,0.00022,1.6E-08,0.00000119,0.00000168,0.00855000,0.00000003,0.00000000
        ///CHS2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CHS {
            get {
                return ResourceManager.GetString("CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA200X200X24,71.10,0.2000,0.0240,0.0180,0.0090,0.00906000,0.00003330,0.06060000,0.00023500,0.00000182,0.00000000
        ///EA200X200X20,59.90,0.2000,0.0200,0.0180,0.0090,0.00763000,0.00002850,0.06110000,0.00019900,0.00000107,0.00000000
        ///EA200X200X18,54.30,0.2000,0.0180,0.0180,0.0090,0.00691000,0.00002600,0.06130000,0.00018100,0.00000079,0.00000000
        ///EA200X200X16,48.50,0.2000,0.0160,0.0180,0.0090,0.00618000,0.00002340,0.06160000,0.00016200,0.00000056,0.00000000
        ///EA150X150X18,40.10,0.1500,0.0180,0.0160,0.0080,0.0051200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RHS50X30X3,3.41,0.0500,0.0300,0.0030,0.000434000,0.000000136,0.000005430,0.000006880,0.017700000,0.000000059,0.000003960,0.000004760,0.011700000,0.000000135,0.000000000
        ///RHS50X30X3.2,3.61,0.0500,0.0300,0.0032,0.000460000,0.000000142,0.000005680,0.000007250,0.017600000,0.000000062,0.000004130,0.000005000,0.011600000,0.000000142,0.000000000
        ///RHS50X30X3.6,4.01,0.0500,0.0300,0.0036,0.000510000,0.000000154,0.000006160,0.000007940,0.017400000,0.000000067,0.000004450,0.000005460,0.011400000,0.000000154,0.000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RHS {
            get {
                return ResourceManager.GetString("RHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHS40X40X3,3.41,0.0400,0.0400,0.0030,0.00043400,0.00000010,0.01500000,0.00000489,0.00000597,0.00000016,0.00000000
        ///SHS40X40X3.2,3.61,0.0400,0.0400,0.0032,0.00046000,0.00000010,0.01490000,0.00000511,0.00000628,0.00000017,0.00000000
        ///SHS40X40X3.6,4.01,0.0400,0.0400,0.0036,0.00051000,0.00000011,0.01470000,0.00000554,0.00000688,0.00000018,0.00000000
        ///SHS40X40X4,4.39,0.0400,0.0400,0.0040,0.00055900,0.00000012,0.01450000,0.00000591,0.00000744,0.00000020,0.00000000
        ///SHS40X40X5,5.28,0.0400,0.0400,0.0050,0.00067300, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SHS {
            get {
                return ResourceManager.GetString("SHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UB1016X305X487,486.70,1.0363,0.3085,0.0300,0.0541,0.0300,0.06200000,0.01021884,0.01972200,0.02320800,0.40600000,0.00026721,0.00173200,0.00279900,0.06570000,0.00004299,0.00006440
        ///UB1016X305X437,437.00,1.0261,0.3054,0.0269,0.0490,0.0300,0.05570000,0.00910322,0.01774300,0.02076900,0.40400000,0.00023447,0.00153500,0.00246700,0.06490000,0.00003185,0.00005600
        ///UB1016X305X393,392.70,1.0159,0.3030,0.0244,0.0439,0.0300,0.05000000,0.00807503,0.01589700,0.01853800,0.40200000,0.00020496,0.00135300,0.00216700,0.0640000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UB {
            get {
                return ResourceManager.GetString("UB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBP356x368x174,173.90,0.3614,0.3785,0.0203,0.0204,0.0152,0.02210000,0.00051009,0.00282300,0.00318600,0.15200000,0.00018463,0.00097600,0.00149700,0.09130000,0.00000330,0.00000537
        ///UBP356x368x152,152.00,0.3564,0.3760,0.0178,0.0179,0.0152,0.01940000,0.00043972,0.00246800,0.00276700,0.15100000,0.00015877,0.00084500,0.00129300,0.09050000,0.00000223,0.00000455
        ///UBP356x368x133,133.00,0.3520,0.3738,0.0156,0.0157,0.0152,0.01690000,0.00037983,0.00215800,0.00240600,0.15000000,0.00013680,0.00073200,0.00111800,0.0899000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UBP {
            get {
                return ResourceManager.GetString("UBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UC356x406x634,633.90,0.4746,0.4240,0.0476,0.0770,0.0152,0.08080000,0.00274845,0.01158200,0.01423500,0.18400000,0.00098125,0.00462900,0.00710800,0.11000000,0.00013720,0.00003880
        ///UC356x406x551,551.00,0.4556,0.4185,0.0421,0.0675,0.0152,0.07020000,0.00226938,0.00996200,0.01207600,0.18000000,0.00082671,0.00395100,0.00605800,0.10900000,0.00009240,0.00003110
        ///UC356x406x467,467.00,0.4366,0.4122,0.0358,0.0580,0.0152,0.05950000,0.00183003,0.00838300,0.01000300,0.17500000,0.00067834,0.00329100,0.00503400,0.10700000,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UC {
            get {
                return ResourceManager.GetString("UC", resourceCulture);
            }
        }
    }
}
